### ISSUE TITLE
Reaction Roles not responding

### ISSUE THREAD

**Issue by master3395** [ItzPike/DBM-Rawdata-Releases#39]
Hello.

I am trying to use the Reaction Role for Discord.js V12
Not sure if it's supported for that yet?

![image](https://user-images.githubusercontent.com/4199669/89821415-d4106e00-db4e-11ea-9491-2a101b17e4e2.png)

![image](https://user-images.githubusercontent.com/4199669/89821457-decb0300-db4e-11ea-884b-7ec68946df07.png)

Not sure if this is related to the removal of roles in the command when i click the emoji and unclick it.
![image](https://user-images.githubusercontent.com/4199669/89821526-028e4900-db4f-11ea-9f6d-e05e0ed83a2e.png)

**Comment by ItzPike** [comment]
As a few troubleshooting steps, I would first advise to update to the latest version of commands. Make sure you had followed the new steps that required for the commands to work. 

Other than that the error you had posted does not seem to be related since it is speaking of Action #80 which is not part of the command set. 

Please make sure you don't have any other raw event commands hanging around that may interfere. Lastly, I would advise checking the data folder for the rolemenu JSON file. As far as I am aware, it does work on v12.

**Comment by master3395** [comment]
I have the latest mods, i will try and disable all events and see what i get.

**Comment by ItzPike** [comment]
Closed due to lack of activity and comments. You can look for further support through Discord or open up this issue again.
